/**
 * Accesly backend HTTP client. Typed wrappers for each endpoint, retry with
 * exponential backoff, telemetry events. Never touches key material.
 */

export {
  AccesslyApiClient,
  type AccesslyApiClientOptions,
  type IdTokenProvider,
  type Json,
  type RequestOptions,
  type TelemetryEvent,
  type TelemetrySink,
} from './client.js';

export { AccesslyEndpoints } from './endpoints.js';

export {
  AccesslyApiError,
  AuthError,
  GAddressNotBootstrappedError,
  GMissingTrustlineError,
  NetworkError,
  NotFoundError,
  RateLimitError,
  RotateWriteCapExceededError,
  ServerError,
  ValidationError,
  WalletNotEnrolledError,
  errorForResponse,
  type AccesslyApiErrorOptions,
} from './errors.js';

export type {
  Base64String,
  CreateWalletRequest,
  CreateWalletResponse,
  EncryptedFragmentWire,
  FinalizeRecoveryRequest,
  FinalizeRecoveryResponse,
  GetFragment2Request,
  GetFragment2Response,
  GetFragment3Response,
  GetWalletResponse,
  HealthResponse,
  HexString,
  KycStartResponse,
  OrderAction,
  OrderRequest,
  OrderResponse,
  RecoveryOtpRequestInput,
  RecoveryOtpRequestResponse,
  RecoveryOtpVerifyInput,
  RecoveryOtpVerifyResponse,
  SimulateRotateSignerRequest,
  SimulateRotateSignerResponse,
  SimulateRotatePartialRequest,
  SimulateRotatePartialResponse,
  RotatePartialRequest,
  RotatePartialResponse,
  SimulateFinalizeRotationRequest,
  SimulateFinalizeRotationResponse,
  FinalizeRotationRequest,
  FinalizeRotationResponse,
  ActivatableAsset,
  ActivateAssetSimulateRequest,
  AddTrustlineGSimulateRequest,
  AddTrustlineGSimulateResponse,
  AddTrustlineGSubmitRequest,
  AddTrustlineGSubmitResponse,
  BootstrapGSimulateResponse,
  BootstrapGSubmitRequest,
  BootstrapGSubmitResponse,
  SweepGSimulateResponse,
  SweepGSubmitRequest,
  SweepGSubmitResponse,
  RegisterBankAccountRequest,
  RegisterBankAccountResponse,
  SimulateSwapRequest,
  SimulateSwapResponse,
  SimulateSwapSdexResponse,
  SubmitSwapSdexRequest,
  SubmitSwapSdexResponse,
  FinalizeSwapSdexRequest,
  FinalizeSwapSdexResponse,
  SimulateTxRequest,
  SimulateTxResponse,
  SubmitTxRequest,
  SubmitTxResponse,
  TransferAsset,
  WalletActivityEvent,
  WalletActivityResponse,
  WalletBalanceResponse,
  WalletHistoryItem,
  WalletHistoryRequestOptions,
  WalletHistoryResponse,
  WalletUpgradeSimulateRequest,
  WalletUpgradeSimulateResponse,
  WalletUpgradeSubmitRequest,
  WalletUpgradeSubmitResponse,
} from '../types/api.js';
